# Generated by Django 2.2 on 2020-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Укажите наименование планеты'}, max_length=60, unique=True, verbose_name='Наименование')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
