# Generated by Django 2.2 on 2020-03-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Заполните имя!'}, max_length=60, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Planet')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
