# Generated by Django 2.2 on 2020-03-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_recruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(error_messages={'required': 'Заполните текст вопроса!'}, verbose_name='Вопрос')),
            ],
        ),
        migrations.AlterField(
            model_name='recruit',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Planet', verbose_name='Планета обитания'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Planet', verbose_name='Орден')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Questions', verbose_name='Вопрос')),
            ],
        ),
    ]
