# Generated by Django 2.2 on 2020-03-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200321_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question', verbose_name='Вопрос')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Recruit', verbose_name='Рекрут')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Заполните имя!'}, max_length=60, verbose_name='Имя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Planet', verbose_name='Планета')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Запись активна')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Recruit', verbose_name='Рекрут')),
                ('sith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sith', verbose_name='Ситх')),
            ],
        ),
    ]
