# Generated by Django 2.2 on 2020-03-24 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200322_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата ответа'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mentoring',
            unique_together={('recruit', 'sith', 'is_active')},
        ),
    ]
